version: '3.3'
services:
  selenoid:
    image: "aerokube/selenoid"
    command: -listen :4444 -conf /etc/selenoid/browsers.json
    network_mode: bridge
    ports:
      - "4444:4444"
    expose:
          - "4444"
    volumes:
      - "$PWD:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"

