version: '3.3'
services:

  selenoid:
    image: "aerokube/selenoid"
    ports:
      - "4444:4444"
    volumes:
      - "$PWD:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: [ "-conf", "/etc/selenoid/browsers.json",
               "-video-output-dir", "/opt/selenoid/video",
               "-container-network", "autotest_default" ]
    networks:
      - default

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    networks:
      - default



